---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yml
      skip: true

- name: detect docker environment
  ansible.builtin.set_fact:
    is_docker_guest: "{{
      ansible_virtualization_role | default('host') == 'guest' and
      ansible_virtualization_type | default('none') == 'docker' }}"

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: install dependencies
  ansible.builtin.package:
    name: "{{ postfix_dependencies }}"
    state: present
  when:
    - postfix_dependencies | default([]) | count > 0

- name: gathering facts now
  ansible.builtin.setup:

- name: merge postfix configuration between defaults and custom
  ansible.builtin.set_fact:
    postfix_aliases: "{{ postfix_defaults_aliases | union(postfix_aliases) }}"
    postfix_users: "{{ postfix_defaults_users | combine(postfix_users, recursive=True) }}"
    postfix_alias: "{{ postfix_defaults_alias | combine(postfix_alias, recursive=True) }}"
    postfix_default: "{{ postfix_defaults_default | combine(postfix_default, recursive=True) }}"
    postfix_header: "{{ postfix_defaults_header | combine(postfix_header, recursive=True) }}"
    postfix_inet: "{{ postfix_defaults_inet | combine(postfix_inet, recursive=True) }}"
    postfix_mailbox: "{{ postfix_defaults_mailbox | combine(postfix_mailbox, recursive=True) }}"
    postfix_maillog: "{{ postfix_defaults_maillog | combine(postfix_maillog, recursive=True) }}"
    postfix_message: "{{ postfix_defaults_message | combine(postfix_message, recursive=True) }}"
    postfix_postscreen: "{{ postfix_defaults_postscreen | combine(postfix_postscreen, recursive=True) }}"
    postfix_proxy: "{{ postfix_defaults_proxy | combine(postfix_proxy, recursive=True) }}"
    postfix_queue: "{{ postfix_defaults_queue | combine(postfix_queue, recursive=True) }}"
    postfix_recipient: "{{ postfix_defaults_recipient | combine(postfix_recipient, recursive=True) }}"
    postfix_reject: "{{ postfix_defaults_reject | combine(postfix_reject, recursive=True) }}"
    postfix_relay: "{{ postfix_defaults_relay | combine(postfix_relay, recursive=True) }}"
    postfix_sender: "{{ postfix_defaults_sender | combine(postfix_sender, recursive=True) }}"
    postfix_smtp: "{{ postfix_defaults_smtp | combine(postfix_smtp, recursive=True) }}"
    postfix_smtpd: "{{ postfix_defaults_smtpd | combine(postfix_smtpd, recursive=True) }}"
    postfix_transport: "{{ postfix_defaults_transport | combine(postfix_transport, recursive=True) }}"
    postfix_virtual: "{{ postfix_defaults_virtual | combine(postfix_virtual, recursive=True) }}"
    postfix_virtual_backends: "{{ postfix_defaults_virtual_backends | combine(postfix_virtual_backends, recursive=True) }}"
    postfix_tls: "{{ postfix_defaults_tls | combine(postfix_tls, recursive=True) }}"
    #
    postfix_master: "{{ postfix_defaults_master | combine(postfix_master, recursive=True) }}"

- name: validate smtpd tls certificate files
  postfix_validate_certs:
    config: "{{ postfix_smtpd.tls }}"
  when:
    - postfix_smtpd.use_tls | bool
    - postfix_smtpd.tls is defined

- name: validate smtp tls certificate files
  postfix_validate_certs:
    config: "{{ postfix_smtp.tls }}"
  when:
    - postfix_smtp.use_tls | bool
    - postfix_smtp.tls is defined

...
