---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yml
      skip: true

- name: detect docker environment
  ansible.builtin.set_fact:
    is_docker_guest: "{{
      ansible_virtualization_role | default('host') == 'guest' and
      ansible_virtualization_type | default('none') == 'docker' }}"

# - name: update package cache
#   ansible.builtin.package:
#     update_cache: true

- name: install dependencies
  ansible.builtin.package:
    name: "{{ postfix_dependencies }}"
    state: present
  when:
    - postfix_dependencies | default([]) | count > 0

- name: gathering facts now
  ansible.builtin.setup:

- name: merge postfix configuration between defaults and custom
  ansible.builtin.set_fact:
    postfix_smtp: "{{ postfix_defaults_smtp | combine(postfix_smtp, recursive=True) }}"
    postfix_smtpd: "{{ postfix_defaults_smtpd | combine(postfix_smtpd, recursive=True) }}"

- name: validate smtpd tls certificate files
  postfix_validate_certs:
    config: "{{ postfix_smtpd.tls }}"
  when:
    - postfix_smtpd.use_tls | bool
    - postfix_smtpd.tls is defined

- name: validate smtp tls certificate files
  postfix_validate_certs:
    config: "{{ postfix_smtp.tls }}"
  when:
    - postfix_smtp.use_tls | bool
    - postfix_smtp.tls is defined

...
