---

- name: start and enable service
  ansible.builtin.service:
    name: postfix
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - postfix
    - postfix-start-enable-service

...
