---

postfix_inet:
  interfaces:
    - "{{ ansible_default_ipv4.address }}"

postfix_aliases:
  - root: you@yourdomain.org

postfix_smtpd:
  banner: "$myhostname ESMTP $mail_name"
  recipient_restrictions:
    - check_recipient_mx_access
    # - proxy:mysql:/opt/postfix/conf/sql/mysql_mbr_access_maps.cf
    - permit_sasl_authenticated
    - permit_mynetworks
    # - check_recipient_access proxy:mysql:/opt/postfix/conf/sql/mysql_tls_enforce_in_policy.cf
    - reject_invalid_helo_hostname
    - reject_unauth_destination
  data_restrictions:
    - reject_unauth_pipelining
    - permit
  sender_restrictions:
    - reject_authenticated_sender_login_mismatch
    - permit_mynetworks
    - permit_sasl_authenticated
    - reject_unlisted_sender
    - reject_unknown_sender_domain
  relay_restrictions:
    - permit_mynetworks
    - permit_sasl_authenticated
    - defer_unauth_destination
    - reject_unauth_destination
  use_tls: true
  tls:
    cert_file: "/etc/snakeoil/matrix.lan/matrix.lan.pem"
    key_file: "/etc/snakeoil/matrix.lan/matrix.lan.key"

postfix_smtp:
  use_tls: true
  generic_maps_file: "hash:/etc/postfix/generic"
  header_checks_file: "hash:/etc/postfix/header_checks"
  sasl:
    auth:
      enable: false
    password_maps: "hash:/etc/postfix/sasl_passwd"
    security_options: noanonymous
    tls:
      security_options: noanonymous
    mechanism_filter: ""

postfix_tls:
  export_cipherlist:
    - "aNULL"
    - "-aNULL"
    - "HIGH"
    - "MEDIUM"
    - "LOW"
    - "EXPORT"
    - "+RC4"
    - "@STRENGTH"
  preempt_cipherlist: true
  ssl_options:
    - NO_TICKET
    - NO_COMPRESSION
    - NO_RENEGOTIATION

...
