---

postfix_inet:
  interfaces:
    - "{{ ansible_default_ipv4.address }}"

postfix_aliases:
  - root: you@yourdomain.org

postfix_users:
  # TODO - https://github.com/bodsch/ansible-postfix/issues/21
  sasl_auth:
    - username: "postmaster@localhost"
      password: "foofoo"
      host: "mail.foo.bar"
      port: 2525
      description: "sasl credentials for postmaster"
    - username: acc1@gmail.com
      password: passwd2
      host: smtp.gmail.com
      port: 587
    - username: account1@gmail.com
      password: passwd1
    - username: acc2@gmail.com
      password: passwd2
  # https://github.com/bodsch/ansible-postfix/issues/22
  relay: []
#    - description: "relay for account1@gmail.com. see: sasl auth"
#      username: account1@gmail.com
#      host: smtp.gmail.com
#      port: 587
#    - username: acc2@gmail.com
#      host: smtp.gmail.com
#      port: 587

postfix_smtpd:
  banner: "$myhostname ESMTP $mail_name"
  recipient_restrictions:
    - check_recipient_mx_access
    # - proxy:mysql:/opt/postfix/conf/sql/mysql_mbr_access_maps.cf
    - permit_sasl_authenticated
    - permit_mynetworks
    # - check_recipient_access proxy:mysql:/opt/postfix/conf/sql/mysql_tls_enforce_in_policy.cf
    - reject_invalid_helo_hostname
    - reject_unauth_destination
  data_restrictions:
    - reject_unauth_pipelining
    - permit
  sender_restrictions:
    - reject_authenticated_sender_login_mismatch
    - permit_mynetworks
    - permit_sasl_authenticated
    - reject_unlisted_sender
    - reject_unknown_sender_domain
  relay_restrictions:
    - permit_mynetworks
    - permit_sasl_authenticated
    - defer_unauth_destination
    - reject_unauth_destination
  use_tls: true
  tls:
    cert_file: "/etc/snakeoil/matrix.lan/matrix.lan.pem"
    key_file: "/etc/snakeoil/matrix.lan/matrix.lan.key"

postfix_smtp:
  use_tls: true
  generic_maps_file: "hash:/etc/postfix/generic"
  header_checks_file: "hash:/etc/postfix/header_checks"
  sasl:
    auth:
      enable: true
    password_maps: "hash:/etc/postfix/sasl_passwd"
    security_options: noanonymous
    tls:
      security_options: noanonymous
    mechanism_filter: ""

postfix_relay:
  use_tls: true
  host: 'mail.test.com'
  mxlookup: false
  port: 587

postfix_header:
  checks:
    - pattern: "/^Message-ID:.*"
      action: "<!&!/ DUNNO"
    - pattern: /^Message-ID:.*@(porcupine\.org)/"
      action: "reject forged domain name in Message-ID: header: $1"

postfix_virtual:
  aliases:
    - virtual: webmaster@matrix.lan
      alias: personal_email@gmail.com
    - virtual: billandbob@matrix.lan
      alias: bill@gmail.com, bob@gmail.com

postfix_sender:
  canonical_maps:
    - sender: '/^((root|dbsupport|helpdesk).*)matrix[.]lan$/'
      rewrite: tech.nick@matrix.lan
    - sender: root
      rewrite: tech.nick@matrix.lan
    - sender: root@matrix.lan
      rewrite: tech.nick@matrix.lan
  dependent_relayhost_maps:
    - pattern: 'logcheck@yourdomain.org'
      result: 'DUNNO'
    - pattern: 'pflogsumm@yourdomain.org'
      result: 'DUNNO'
    - pattern: '*'
      result: "smtp:{{ ansible_lo['ipv4']['address'] }}:1025"

postfix_recipient:
  canonical_maps_files: ""
  canonical_maps: []

postfix_transport:
  maps:
    - "hash:{{ postfix_maps_directory }}/transport_maps"
#    - "pcre:{{ postfix_maps_directory }}/local_transport"
  transport_maps:
    - pattern: 'root@yourdomain.org'
      result: ':'
    - pattern: '*'
      result: "smtp:{{ ansible_lo['ipv4']['address'] }}:1025"

postfix_postscreen:
  dnsbl_sites:
    - wl.mailspike.net=127.0.0.[18;19;20]*-2
    - hostkarma.junkemailfilter.com=127.0.0.1*-2
    - list.dnswl.org=127.0.[0..255].0*-2
    - list.dnswl.org=127.0.[0..255].1*-4
    - list.dnswl.org=127.0.[0..255].2*-6
    - list.dnswl.org=127.0.[0..255].3*-8
    - ix.dnsbl.manitu.net*2
    - bl.spamcop.net*2
    - bl.suomispam.net*2
    - hostkarma.junkemailfilter.com=127.0.0.2*3
    - hostkarma.junkemailfilter.com=127.0.0.4*2
    - hostkarma.junkemailfilter.com=127.0.1.2*1

postfix_mydestinations:
  - $myhostname
  - "{{ postfix_hostname }}"
  - localdomain
  - localhost
  - localhost.localdomain
  - 192.168.11.10/32

postfix_mynetworks:
  - 127.0.0.0/8
  - 192.168.11.10/32

postfix_tls:
  export_cipherlist:
    - "aNULL"
    - "-aNULL"
    - "HIGH"
    - "MEDIUM"
    - "LOW"
    - "EXPORT"
    - "+RC4"
    - "@STRENGTH"
  preempt_cipherlist: true
  # server_sni_maps: "" # hash:/opt/postfix/conf/sni.map"
  ssl_options:
    - NO_TICKET
    - NO_COMPRESSION
    - NO_RENEGOTIATION

# # postfix_raw_options:
# #   - |
# #     milter_default_action = accept
# #     milter_protocol = 6
# #     smtpd_milters = unix:opendkim/opendkim.sock unix:opendmarc/opendmarc.sock unix:spamass/spamass.sock unix:clamav/clamav-milter.ctl
# #     milter_connect_macros = "i j {daemon_name} v {if_name} _"
# #     policyd-spf_time_limit = 3600

...
